baseURL = "https://nicolasfriedli.ch/"
title = "Nicolas Friedli"

languageCode = "fr"
defaultContentLanguage = "fr"

removePathAccents = true

disableKinds = [ "taxonomy", "term", "robotsTXT"]

cleanDestinationDir = true
enableGitInfo = true
noBuildLock = true

copyright = "Creative Commons BY-SA"

[build]
writeStats = false

[frontmatter]
date = ["date", "lastMod", ":git"]
lastmod = ["lastmod", "date", ":git"]

[markup]
[markup.goldmark.parser]
autoHeadingIDType = "github-ascii"

[markup.tableOfContents]
endLevel = 6

[markup.highlight]
style = "dracula"

[minify]
minifyOutput = true

[minify.tdewolff.html]
keepDefaultAttrVals = false
keepQuotes = true
keepWhitespace = true

[params]
images = ["/images/opengraph.jpg"]

[params.author]
name = "Nicolas Friedli"
email = "hello+rss@nicolasfriedli.ch"

[services]
[services.rss]
limit = 20